/** Auto-generated by scripts/generate-industry-world-pack.mjs — re-run script after changing generator logic. */

export type IndustryWorldRowSnapshot = {
  nParties: number;
  nEvents: number;
  groupByParties: number;
  havingFivePlus: number;
};

export const industryWorldRowCounts: Record<number, IndustryWorldRowSnapshot> = {
  15: {
    "nParties": 45,
    "nEvents": 225,
    "groupByParties": 45,
    "havingFivePlus": 27
  },
  16: {
    "nParties": 46,
    "nEvents": 221,
    "groupByParties": 46,
    "havingFivePlus": 26
  },
  17: {
    "nParties": 46,
    "nEvents": 222,
    "groupByParties": 46,
    "havingFivePlus": 25
  },
  18: {
    "nParties": 47,
    "nEvents": 203,
    "groupByParties": 47,
    "havingFivePlus": 21
  },
  19: {
    "nParties": 46,
    "nEvents": 218,
    "groupByParties": 46,
    "havingFivePlus": 27
  },
  20: {
    "nParties": 43,
    "nEvents": 208,
    "groupByParties": 43,
    "havingFivePlus": 24
  },
  21: {
    "nParties": 42,
    "nEvents": 216,
    "groupByParties": 42,
    "havingFivePlus": 24
  },
  22: {
    "nParties": 45,
    "nEvents": 215,
    "groupByParties": 45,
    "havingFivePlus": 22
  },
  23: {
    "nParties": 50,
    "nEvents": 225,
    "groupByParties": 50,
    "havingFivePlus": 24
  },
  24: {
    "nParties": 42,
    "nEvents": 202,
    "groupByParties": 42,
    "havingFivePlus": 26
  },
  25: {
    "nParties": 48,
    "nEvents": 207,
    "groupByParties": 48,
    "havingFivePlus": 15
  },
  26: {
    "nParties": 49,
    "nEvents": 207,
    "groupByParties": 49,
    "havingFivePlus": 19
  },
  27: {
    "nParties": 44,
    "nEvents": 209,
    "groupByParties": 44,
    "havingFivePlus": 25
  },
  28: {
    "nParties": 51,
    "nEvents": 199,
    "groupByParties": 51,
    "havingFivePlus": 17
  },
  29: {
    "nParties": 48,
    "nEvents": 211,
    "groupByParties": 48,
    "havingFivePlus": 22
  },
  30: {
    "nParties": 47,
    "nEvents": 215,
    "groupByParties": 47,
    "havingFivePlus": 26
  },
};
