import type { World } from '@/data/courses/types';
import { buildWorld } from '@/data/courses/worldFactory';
import type { InterviewBankPackJson } from './packTypes';
import pack from './generated/interviewBankPack.json';

/**
 * 300+ LeetCode-style analytics drills on Summit schema.
 * Generated by scripts/generate-interview-bank.mjs (original scenarios — not scraped from third-party sites).
 */
export const interviewBankWorlds: World[] = (pack as InterviewBankPackJson).worlds.map((w) =>
  buildWorld(
    {
      id: w.id,
      name: w.name,
      subtitle: w.subtitle,
      theme: w.theme,
      description: w.description,
      database: w.database,
      icon: w.icon,
      color: w.color,
      prerequisites: w.prerequisites,
    },
    w.levels,
  ),
);
